import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
});

// Копирование дополнительных файлов в dist
function copyToDist() {
	if (!fs.existsSync("dist")) {
		fs.mkdirSync("dist", { recursive: true });
	}

	// Копируем необходимые файлы
	fs.copyFileSync("manifest.json", "dist/manifest.json");
	fs.copyFileSync("styles.css", "dist/styles.css");

	console.log("✅ Файлы скопированы в dist папку");
}

if (prod) {
	await context.rebuild();
	copyToDist();
	process.exit(0);
} else {
	await context.watch();
	copyToDist();
}
